### PR TITLE
CTRL + H (not CTRL + BACKSPACE) deletes the most previous whole word

### PR DESCRIPTION
**Pull request by LucasLarson**

### CODE REVIEW

**Comment by mcornella** [comment]
They both use the same key binding, so they're interchangeable. In my case, I use it for CTRL+BACKSPACE so the comment is correct.

**Comment by LucasLarson** [comment]
Sorry for the interruption then! I couldn’t get it to work with macOS’s <kbd>delete</kbd> or <kbd title=Function>fn</kbd>+<kbd>delete</kbd>. Can I ask if you’re on another OS?

**Comment by mcornella** [comment]
Hmm yeah I'm on a PC. You can try to find the key binding for the keys you want with `CTRL`+`V`, then pressing the keys you want. That should print the key binding in the command prompt, which you can use in the `bindkey` command.

**Comment by mcornella** [comment]
Let me know the key binding if you find it, you've picked my interest!

**Comment by LucasLarson** [comment]
> find the key binding for the keys you want with `CTRL`+`V`, then pressing the keys you want

Thanks for the tip! I’ll definitely let you know.

Notes to self:
Pressing <kbd title=⌃>control</kbd>+<kbd>V</kbd> then <kbd title=⌃>control</kbd>+<kbd>delete</kbd> (there’s no “backspace” on most Macs) gives me `^?`, but that seems to be the one combination I can’t make work with `bindkey`, but I don’t see why.

I _can_ get `^H` to work if I turn on this setting in iTerm2 preferences, but it comes with a warning:
[`^H` considered harmful]()

**Comment by LucasLarson** [comment]
I just ran `omz_diagnostic_dump` and partway through are my `bindkey`s. None of them appear customized (no surprise) but I see `"^H"` as my `backward-delete-char`&nbsp;¯\\\_(ツ)_/¯

**Pull request closed without merging**
